### ISSUE TITLE
There are new level portraits

### ISSUE THREAD

**Issue by Js41637** [Fuyukai/OWAPI#135]
I will look into fetching the new IDs if and when the websites update.
![image](https://cloud.githubusercontent.com/assets/6258213/22270949/44703500-e2e6-11e6-99a1-4fcb22211227.png)

p.s. thanks blizzard web devs

**Comment by azah** [comment]
I'm honestly amazed that there are people who are level 2,000+. wtf.

**Comment by SunDwarf** [comment]
Petition to make the rank return `LOSER` instead of a number

**Comment by SunDwarf** [comment]
@Js41637 any update on this?

**Comment by Js41637** [comment]
The website has still not updated to use new portraits, currently anyone over the max level just uses the golden border with 5 stars. I tried manually searching running my script trying about 1000 different IDs to see if I could find any of the images but I doubt they've even added them anywhere on the website yet. Or they use different IDs, either way. I still cannot find them.

**Comment by SunDwarf** [comment]
Of course not. I wonder if Blizzard will ever update the website or if I'm gonna have to spend a month reverse engineering the game's communication format to the servers.

**Comment by Js41637** [comment]
They obviously don't care very much about the website or stats in general I think. I mean even the game has no stats for any arcade games which is mildly annoying.

The last time the website was broken it took a couple months before it got fixed. There are currently a few broken things on the website now so maybe in a couple months we'll get new portraits :)

**Comment by azah** [comment]
I suppose this and gold borders now need to be implemented.

**Comment by Js41637** [comment]
Gold borders are already added. I still can't add the new portraits as they still haven't been added to the website.

**Comment by azah** [comment]
Ah alright my bad. Thanks, Blizzard

**Comment by Js41637** [comment]
Status update: They're still not added.

**Comment by Js41637** [comment]
Status update: They're still not added.

**Comment by SunDwarf** [comment]
4 months later! I guarantee they're never going to be updated.

**Comment by Jadeskycore** [comment]
I bet the will update them. Not now, someday

**Comment by Js41637** [comment]
Well they just added new stats to the career profiles in PTR, surely they will update the site sometime within the next year.,,

**Comment by Js41637** [comment]
Status update: They're still not added.

**Comment by Js41637** [comment]
Status update: They're still not added.

**Comment by KingJP** [comment]
Status update: They're still not added.

**Comment by SunDwarf** [comment]
This is basically never gonna happen.

**Comment by Js41637** [comment]
woah u just changed ur image

**Comment by Js41637** [comment]
If only they could add features as fast as they break things.
![image](https://user-images.githubusercontent.com/6258213/33466009-3f8d020e-d69f-11e7-989d-d2a0ace16b5f.png)

**Comment by SunDwarf** [comment]
I don't think they're ever gonna get added.

**Comment by Js41637** [comment]
Status update: They're still not added.

**Comment by Fuyukai** [comment]
This bug is older than this project

**Comment by Js41637** [comment]
Status update: They're still not added.

Even after they added private profiles and endorsements.

**Comment by Js41637** [comment]
They will never be added + it's not even possible to get them anymore. Thanks blizz.
