### ISSUE TITLE
Rate Limited

### ISSUE THREAD

**Issue by jwalkss** [Fuyukai/OWAPI#224]
## Issue

What is the rate limit for this API? Im being rate limited on my pull requests and i cant seem to find any specifics on the allowed requests per sec/min/hour for this API.  

Im attempting to iterate through a list of profile ids, pulling the hero data for each profile. Iv varied my sleep time between pull requests several times, but keep getting rate limited.

'https://owapi.net/api/v3/u/{}/heroes'

**Comment by Fuyukai** [comment]
It's 1req/1s for normal requests, and 1req/5s for blob requests.

**Comment by jwalkss** [comment]
Thank you. Im having an issue, Im iterating through a list of profile ids. After 3 attempts, i made it through ~ 160/200 requests each time before a 'response error 502' is returned. How do i resolve this? 

```
@on_exception(expo, RateLimitException, max_tries=3)
@limits(1, period=2)
def call_api(url):
    response = s.get(url)     
    if response.status_code != 200:
        raise Exception('API response: {}'.format(response.status_code))       
    return response.json()    

with requests.Session() as s:
    s.headers = {'User-Agent': ()}  

data=[]
for i in tqdm(range(len(Id))):
    url= 'https://owapi.net/api/v3/u/{}/heroes'.format(Id[i])    
    data.append(call_api(url))
```

**Comment by Fuyukai** [comment]
On the event of a 502 you should retry.
