### ISSUE TITLE
UTF8 or other formating Issue

### ISSUE THREAD

**Issue by ToxicToast** [Fuyukai/OWAPI#225]
## Issue

Tried to get the Profile of a colleague of mine
His Name is "SUPPENLÖFFEL"
Instead of the "ö" it gets shown as "%C3%B6"

## Links that cause the issue
`https://owapi.net/api/v3/u/SUPPENL%C3%96FFEL-21611/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [ x ] Google/Search previous issues to make sure it hasn't been answered before.

* [ x ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by justalemon** [comment]
This is called URL Encoding, and happens with non US characters.

For example, Ñandu is the spanish word for Rhea. If you search Ñandu in Google, the URL will look like `https://www.google.cl/search?q=%C3%B1andu`.

You can read more about this on [Wikipedia](https://en.wikipedia.org/wiki/Percent-encoding) and [w3schools](https://www.w3schools.com/tags/ref_urlencode.asp).
