### ISSUE TITLE
Error in dependencies, add yarl<1.2

### ISSUE THREAD

**Issue by dfreelan** [Fuyukai/OWAPI#226]
## Issue

I couldn't install using the default instructions, I had to change the Pipfile.

I just appended the following line:
yarl = "<1.2"

Without it I was getting the runtime error:
"TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden"

**Comment by dfreelan** [comment]
Also to anybody else who gets confused running this, if you want uvloop for the optimized version you need to add 

uvloop="==0.9.1"

To the Pipfile


That might be nice to add in the readme if you don't want that installed by default

**Comment by KingJP** [comment]
I added uvloop in PullRequest #233 
There was no problem for me using yarl. Which Linux distribution do you use?

**Comment by dfreelan** [comment]
Ubuntu. Here's the output of lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial


and uname -a (hostname excluded)

Linux *** 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
