### ISSUE TITLE
Heads up: profiles will become "private by default" in a few weeks

### ISSUE THREAD

**Issue by brakhane** [Fuyukai/OWAPI#227]
One of the upcoming changes alongside LFG is the ability to limit profile visibililty. By default they will be private.

I don't think there is anything that can be done about it, I guess this is more of a "don't spend much time on OWAPI in the next few weeks, as it might become basically useless" warning.

**Comment by dogancana** [comment]
From developer update, what I understood is they will introduce 'Find a group' feature into game and profiles will be private in that feature. Do you have source for private profiles in playoverwatch.com ?

**Comment by Js41637** [comment]
It's just logical, if they support private profiles in game then logically they would apply the same setting to the career pages. Call it an educated guess.

The joke above is the Overwatch hardly ever fix/update the site as it is so they might not even do it here.

**Comment by Marilyth** [comment]
Seems like they actually disabled player profiles at playoverwatch.com

At least I cant't seem to find anybody I used to find.
e.g. https://playoverwatch.com/en-us/career/pc/Marilyth-2256
Just leads to profile not found or internal error.

**Comment by KingJP** [comment]
I think they are currently working on the website.

Let’s wait till they are finished.

Hopefully they fix the Brigit Hero specific stats :D

 

Von: Marilyth <notifications@github.com> 
Gesendet: Freitag, 8. Juni 2018 13:50
An: Fuyukai/OWAPI <OWAPI@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Fuyukai/OWAPI] Heads up: profiles will become "private by default" in a few weeks (#227)

 

Seems like they actually disabled player profiles at playoverwatch.com

At least I cant't seem to find anybody I used to find.
e.g. https://playoverwatch.com/en-us/career/pc/Marilyth-2256
Just leads to profile not found or internal error.

**Comment by Fuyukai** [comment]
I predict it's gonna be an internal error forever now

**Comment by iAxel** [comment]
site again functions

**Comment by brakhane** [comment]
Now that the patch is live, it's not as worse as feared, but still bad. Private profiles will hide everything except SR, Level and Endorsements
