### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by XEQTIONR** [Fuyukai/OWAPI#230]
## Issue
Hi,

The api seems down. Any ideas on when it'll be fixed?
Try the test url
https://owapi.net/api/v3/u/Dad-12262/blob
(Describe it simply here).

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/Dad-12262/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [ ] Google/Search previous issues to make sure it hasn't been answered before.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by justalemon** [comment]
The API is not down, but it has the problems mentioned in #229.

![imagen](https://user-images.githubusercontent.com/11861253/42016521-d68985fa-7a79-11e8-971c-38a31e92c286.png)

**Comment by Fuyukai** [comment]
#229
