### ISSUE TITLE
AttributeError(\"'NoneType' object has no attribute 'findall'\",)

### ISSUE THREAD

**Issue by restray** [Fuyukai/OWAPI#232]
## Issue

Get 

` {"exc": "AttributeError(\"'NoneType' object has no attribute 'findall'\",)", "msg": "please report this!", "error": 500} `

But there is 3seconds that was working great...

## Links that cause the issue

`https://owapi.net/api/v3/u/Restray-21985/blob`

Thanks you, You're API is awesome !

**Comment by restray** [comment]
Reworking, sorry !

**Comment by KingJP** [comment]
The URL is working in my case.
Do you call the API locally?
