### ISSUE TITLE
New Endorsement Levels need to be added.

### ISSUE THREAD

**Issue by Js41637** [Fuyukai/OWAPI#235]
Users Endorsement level needs to be added.

You can also get the individual numbers for each endorsement which are;

 * Shotcaller
 * Good Teammate
 * Good Sportsmanship

You can find the values for these in the HTML, see image;

![image](https://user-images.githubusercontent.com/6258213/42257127-6b8e578e-7f98-11e8-8f99-925fc793549c.png)

**Comment by OverDodo** [comment]
Where exactly is this html code? I cant find it in the playoverwatch stats page. I'd love to know that

**Comment by Js41637** [comment]
It's on your profile page? Just search for it.

**Comment by OverDodo** [comment]
For me it is not. 
I looks like this: http://prntscr.com/k61vsb

**Comment by Js41637** [comment]
It's literally in the image you posted, they must have changed the markup slightly.

**Comment by OverDodo** [comment]
Well it doesnt show the 3 values as you can clearly see. Do you know where to find them now? Some sites like owedv can still show you the values

**Comment by Js41637** [comment]
Ah yes, in true Blizzard fashion they have changed them, they are now percentages, I don't know how sites like owedv get the values. It's possible they are incorrect or they have figured something out.
