### ISSUE TITLE
No Data Being Returned

### ISSUE THREAD

**Issue by Skillz4Killz** [Fuyukai/OWAPI#242]
## Issue

Searching for any information through the REST API is returning empty objects with no data. Even fetching the exact URLS provided on the `api.md` docs it will still return similar empty objects.

EDIT: May be similar to #229 but since that issue was closed I think perhaps this has occurred again.

```js
{
  "error": "Private",
  "_request": {
    "api_ver": 3,
    "route": "/api/v3/u/Dad-12262/blob"
  }
}
```

```js
{
  "us": {
    "stats": {
      "quickplay": {
        "overall_stats": {
          "comprank": 4704
        },
        "average_stats": [],
        "game_stats": []
      },
      "competitive": {
        "overall_stats": {
          "comprank": 4704
        },
       "average_stats": [],
       "game_stats": []
      }
    }
  },
  "_request": {
    "api_ver": 3,
    "route": "/api/v3/u/Epzz-2845/stats"
  },
  "eu": {
    "stats": {
      ..........
}
````
## Links that cause the issue

`https://owapi.net/api/v3/u/Dad-12262/blob`
`http://owapi.net/api/v3/u/Epzz-2845/stats`

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by Doezer** [comment]
Yes this is normal, the author has not had the time yet to review the entire system since the switch to private profiles.
The comprank presence is coming from my commits ([#236](https://github.com/Fuyukai/OWAPI/pull/236)) but I needed only that for my own app.

**Comment by Fuyukai** [comment]
Private profiles return just a private blob (which I guess I can add to the API docs).

Until I get back from EuroPython, use the /blob endpoint and not stats/heroes endpoints as blob is known working for public profiles and the other two aren't, for whatever reason.

**Comment by Fuyukai** [comment]
Very late, but this is fixed.
