### ISSUE TITLE
Owapi.net SSL handshake failed

### ISSUE THREAD

**Issue by koen20** [Fuyukai/OWAPI#244]
## Issue
Hello,
Since Sunday owapi.net stopped working. I keep getting error 525 SSL handshake failed.

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/Dad-12262/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by Fuyukai** [comment]
Cloudflare didn't like my TLS setup for some reason. Fixed.
