### ISSUE TITLE
New hero in the live version of the API

### ISSUE THREAD

**Issue by EndBug** [Fuyukai/OWAPI#248]
## Issue

Wrecking ball has been added to the hero pool with #247, but it's not supported yet by the live API.

**Comment by Fuyukai** [comment]
Pushed to live.

**Comment by EndBug** [comment]
Uhm, I'm getting an internal error:
`{"error": 500, "exc": "AttributeError(\"'NoneType' object has no attribute 'lower'\",)", "msg": "please report this!"}`

Link: https://owapi.net/api/v3/u/EndBug-2119/blob?format=json_pretty
