### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by shdudwns** [Fuyukai/OWAPI#250]
root@ubuntu:~/OWAPI# PYTHONPATH=. pipenv run asphalt run -l uvloop config.ymlError: the command asphalt could not be found within PATH or Pipfile's [scripts].
root@ubuntu:~/OWAPI# cp config.example.yml config.                           root@ubuntu:~/OWAPI# PYTHONPATH=. pipenv run asphalt run config.yml
Error: the command asphalt could not be found within PATH or Pipfile's [scripts].

**Comment by shdudwns** [comment]
![screenshot_20180927-003736_juicessh](https://user-images.githubusercontent.com/26038520/46091340-98d05480-c1ed-11e8-8ae6-a9186fbf7512.jpg)
@Fuyukai

**Comment by Fuyukai** [comment]
You need to use Python 3.

**Comment by shdudwns** [comment]
@Fuyukai i use Python 3

**Comment by shdudwns** [comment]
![screenshot_20180927-004225_juicessh](https://user-images.githubusercontent.com/26038520/46091660-3f1c5a00-c1ee-11e8-90bc-dcb86304abca.jpg)

**Comment by Fuyukai** [comment]
You're not running pipenv with Python 3.

**Comment by shdudwns** [comment]
How?
