### ISSUE TITLE
prestige level isn't available?

### ISSUE THREAD

**Issue by hakushakusama** [Fuyukai/OWAPI#251]
## Issue

(prestige level isn't available, it returns NULL, same for the icon).

## Links that cause the issue

(when i try to get rank like that`$decoded['eu']['stats']['competitive']['overall_stats']['comprank']`, its OK and easy, but when i try to get the prestige its showing `NULL`  
)

`https://owapi.net/api/v3/u/Dad-12262/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [ ] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by hakushakusama** [comment]
Admin please can we have a fix for that? é_è

**Comment by Js41637** [comment]
The level portraits use a different URL now making the original code that determines the level based off the image url no longer works.

**Comment by Js41637** [comment]
Because they now don't use a predictable URL pattern and no longer sync up with the game (the original url IDs matched up with the IDs of the portraits in the game), it is essentially impossible to properly tell the level without doing some image recognition.

**Comment by Js41637** [comment]
I dunno if anyone can be bothered to do this but there is actually an API that will return a users level however it depends on some random user ID that can be found in a users profile page. Returns JSON containing the level, their avatar, whether the profile is private in an array of platforms (I think).

I think it will be too much effort to add it to this API but maybe we could try and scrape the users ID and return it as well and if someone really wants the level they can use the API themselves??

### URL in question
https://playoverwatch.com/en-us/career/platforms/302618485

### Where the ID is located
![image](https://user-images.githubusercontent.com/6258213/46571544-0fbdd800-c9ba-11e8-8c7d-4f9a0d567967.png)

**Comment by Fuyukai** [comment]
Wow if only Blizzard could extend that into a full API

**Comment by Js41637** [comment]
Nice joke.

**Comment by TeKrop** [comment]
> I dunno if anyone can be bothered to do this but there is actually an API that will return a users level however it depends on some random user ID that can be found in a users profile page. Returns JSON containing the level, their avatar, whether the profile is private in an array of platforms (I think).
> 
> I think it will be too much effort to add it to this API but maybe we could try and scrape the users ID and return it as well and if someone really wants the level they can use the API themselves??
> ### URL in question
> #### 1 Platform
> 
> https://playoverwatch.com/en-us/career/platforms/302618485
> #### 2 Platforms
> 
> https://playoverwatch.com/en-us/career/platforms/347449534
> ### Where the ID is located
> 
> ![image](https://user-images.githubusercontent.com/6258213/46571544-0fbdd800-c9ba-11e8-8c7d-4f9a0d567967.png)

I found an alternate url to do the same job without the ID, even if we don't know when Blizzard will change it xD It's used in player search, so results are not 100% accurate, but you should be able to find the right player using the platform and the name (for ps4/xbl) or btag (for pc) of the player you are search for.

### URL
https://playoverwatch.com/en-us/search/account-by-name/[NameOrBattleTag]

### Exemple result
![screenshot-nanoboost](https://user-images.githubusercontent.com/6080933/46574303-5ce18000-c9a1-11e8-9b61-1acb4de7da28.png)

**Comment by relaera** [comment]
Pull request #270 has been made to correct this.

**Comment by relaera** [comment]
#270 has been merged into master. You should be able to pull this fix into your code
