### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1,585'

### ISSUE THREAD

**Issue by laam4** [Fuyukai/OWAPI#254]
## Issue

This player has over 1000 hours in quickplay and blizzard has now(?) added thousands separator to the time played value. I have cached API response from last Wednesday where this still worked fine.

```json
"quickplay" : {
...
    "game_stats" : {
        ...
        "time_played" : 1581.0,
        ...
    }
}
```

## Links that cause the issue

`https://owapi.net/api/v3/u/Peittomies-2105/stats`
the culprit: `https://i.imgur.com/P3REAZ5.png`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by Fuyukai** [comment]
Fixed alongside some other issue.
