### ISSUE TITLE
win_rate is 0 for competitive

### ISSUE THREAD

**Issue by koen20** [Fuyukai/OWAPI#257]
## Issue
The competitive overall_stats are wrong. The amount of games played, losses and win_rate is 0.
The data is correct in game_stats

## Links that cause the issue

(Surround the links with backticks. Use triple backticks for multiple lines.)

`https://owapi.net/api/v3/u/koen-21591/blob`

Hi! Thank you for helping OWAPI by submitting an issue.
Before you submit, please make sure you've done the following:

* [x] Google/Search previous issues to make sure it hasn't been answered before.

* [x] Ask if this is an *OWAPI* issue, or a *Linux* issue, etc.
    * OWAPI requires Python 3.5 or higher installed on a UNIX machine, and it's not really our job to troubleshoot random Linux errors.

Thanks!

**Comment by Doezer** [comment]
That's because Blizzard changed the way stats blocks are displayed, they're random now. Needs a bit of tweaking but I'm working on it
