### ISSUE TITLE
Error with Redis on owapi.net

### ISSUE THREAD

**Issue by Doezer** [Fuyukai/OWAPI#259]
## Issue

When searching for a profile (no specific condition apart from using json_pretty formatting), the API responds with : 
`{"exc": "ReplyError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)", "error": 500, "msg": "please report this!"}`

It is temporary and works a few minutes later, but it happens pretty frequently.

## Links that cause the issue

`https://owapi.net/api/v3/u/kXb-2578/blob?format=json_pretty`

**Comment by Fuyukai** [comment]
Fuck if I know. Journalctl shows nothing, my disk isn't full and the VPS has enough memory. Just retry.

**Comment by Doezer** [comment]
Alright thanks for the info.
