### ISSUE TITLE
quickPlayStats and competitiveStats return empty arrays

### ISSUE THREAD

**Issue by Nuura** [Fuyukai/OWAPI#265]
## Issue

Hello ! I'm using this route : GET https://ow-api.com/v1/stats/:platform/:region/:battletag/profile and i can't find anything in quickPlayStats and competitiveStats when i'm doing a request, is that normal ? I can get img, rank without any problem, but for these two stats i can't, array is empty each time.

## Links that cause the issue

``` 
request('https://ow-api.com/v1/stats/pc/eu/'+pseudo+'/profile', { json: true }, (err, res, body) => {
 if (err) { return console.log(err); }

//Working with informations here

});
```

Thanks!

**Comment by Fuyukai** [comment]
Wrong repo.

**Comment by Nuura** [comment]
Ok.
