### ISSUE TITLE
Some profiles returning "unsupported operand type(s) for +: 'int' and 'NoneType'"

### ISSUE THREAD

**Issue by Yernemm** [Fuyukai/OWAPI#276]
## Issue

When using the API for some profiles, it returns:

```
{"exc": "TypeError(\"unsupported operand type(s) for +: 'int' and 'NoneType'\",)", "error": 500, "msg": "please report this!"}
```

Most accounts I tested work fine, only a small amount of public accounts return this error. 

## Links that cause the issue

`https://owapi.net/api/v3/u/Yer-21521/stats`

**Comment by relaera** [comment]
This is my fault. PR incoming

**Comment by relaera** [comment]
#277 filed
This bug was introduced by #274. Sorry about that!

**Comment by relaera** [comment]
@Yernemm - The PR was merged into master. Can you confirm that the issue is fixed and close it, if so? The link you posted above works for me
