### ISSUE TITLE
"ValueError(\"could not convert string to float: 'null'\",)"

### ISSUE THREAD

**Issue by GeoffroyBERNARD** [Fuyukai/OWAPI#278]
## Issue

Sometimes I'm getting this error 
```{
"error": 500, 
"msg": "please report this!",
"exc": "ValueError(\"could not convert string to float: 'null'\",)"
}```

It happens from time to times on different btags.

Also sometimes I'm getting an objet with every value listed as undefined.

## Links that cause the issue

`https://owapi.net/api/v3/u/BaronGOF-2402/blob`

**Comment by GeoffroyBERNARD** [comment]
I've noticed that play overwatch is always buggy like on this screen so it might be related if you gather data from here
![image](https://user-images.githubusercontent.com/37252479/52227528-113bd600-28b0-11e9-997a-fdda80b9893d.png)

**Comment by relaera** [comment]
Not much can be done for these. It's an issue on the Blizz side rendering the webpage. Literally, just try again in a minute or so

**Comment by jpylypiw** [comment]
Seems like Blizzard did a lot of stuff on their Website early this year.
The BattleTag worked on my local Fork. It seems like Blizzard fixed this issue.
