### ISSUE TITLE
"ValueError(\"invalid literal for int() with base 10: '1,262'\",)"

### ISSUE THREAD

**Issue by SlimShadyIAm** [Fuyukai/OWAPI#288]
## Issue
As the title says, I get an error 500 when making a request with a specific battletag, and the exception is as above.

I have no issues making requests for this battletag from other similar API's, just this one.

## Links that cause the issue
`https://owapi.net/api/v3/u/FullyTorqued-21192/blob`

**Comment by jpylypiw** [comment]
I tested the BattleTag and got the same error on my local fork.
It seems like the player spent a lot of time in overwatch and has reached some values no other player has reached.
His value of `time played` in Quickplay is `1,288:11:36`.
Maybe think this failed while parsing.
I created a fix and I am testing it now on my local fork.

New Code in "owapi/util.py":
```
def int_or_string(val: str):
    """
    Loads a value from MO into either an int or string value.

    String is returned if we can't turn it into an int.
    """
    val = val.replace(",", "")
    try:
        return float(val)
    except ValueError:
        return val
```

Current Code:
```
def int_or_string(val: str):
    """
    Loads a value from MO into either an int or string value.
    String is returned if we can't turn it into an int.
    """
    new_s = val.replace(",", "")
    try:
        return float(new_s)
    except ValueError:
        return val
```

After some testing I will create a Pull Request if this worked.

**Comment by jpylypiw** [comment]
I have to admit that the changes I made are shit and I have to think about this again.
Sorry for that, but I dont like this changes anymore.
