### ISSUE TITLE
Redis on public API is dead

### ISSUE THREAD

**Issue by Wruczek** [Fuyukai/OWAPI#296]
Getting error 500: `ReplyError('MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.',)` for all requests.

**Comment by jpylypiw** [comment]
Hi @Wruczek!

the live version should be used for testing purposes. For production OWAPI should be installed locally for rate limiting and performance.

Anyway someone should check the Redis logs on the live server.

thanks for reporting!

**Comment by Fuyukai** [comment]
For whatever reason redis couldn't allocate memory (with a gig remaining?). Fixed it.
